genius_login:
    pattern: /logowanie
    defaults: {_controller: GeniusDesignDesktopPanelBundle:Security:login}
    
genius_login_check:
    pattern: /zaloguj
    
genius_logout:
    pattern: /wyloguj
    
    
genius_news_edit:
    pattern: /aktualnosci/edycja/{newsId}/{language}
    defaults: {_controller: GeniusDesignDesktopPanelBundle:News:edit, language: ''}
    
genius_news_list:
    pattern: /aktualnosci/{language}
    defaults: {_controller: GeniusDesignDesktopPanelBundle:News:list, language: ''}


genius_content_edit:
    pattern: /tresci/edycja/{contentSlug}/{language}
    defaults: {_controller: GeniusDesignDesktopPanelBundle:Content:edit, language: ''}
    requirements:
        contentSlug: "[\w-]+"
        language: "[\w-]+"

genius_content_list:
    pattern: /tresci/{language}
    defaults: {_controller: GeniusDesignDesktopPanelBundle:Content:list, language: ''}
    requirements:
        language: "[\w-]+"
    
    
genius_test:
    pattern: /test
    defaults: {_controller: GeniusDesignDesktopPanelBundle:Default:index}
    
genius_homepage:
    pattern: /
    defaults: {_controller: GeniusDesignDesktopPanelBundle:Default:index}


