genius_login:
    pattern: /logowanie
    defaults: {_controller: GeniusDesignBackendBundle:Security:login}
    
genius_login_check:
    pattern: /zaloguj
    
genius_logout:
    pattern: /wyloguj
    
    
    
genius_news_edit:
    pattern: /{languageCode}/aktualnosci/edycja/{newsSlug}
    defaults: {_controller: GeniusDesignBackendBundle:News:edit, languageCode: ''}
    requirements:
        contentSlug: "[\w-]+"
        languageCode: "[\w-]+"
        
genius_news_add:
    pattern: /{languageCode}/aktualnosci/dodaj
    defaults: {_controller: GeniusDesignBackendBundle:News:add, languageCode: ''}
    requirements:
        languageCode: "[\w-]+"

genius_news_delete:
    pattern: /{languageCode}/aktualnosci/usun/{newsSlug}
    defaults: {_controller: GeniusDesignBackendBundle:News:delete, languageCode: ''}
    requirements:
        newsSlug: "[\w-]+"
        languageCode: "[\w-]+"
        
genius_news_toggle_published:
    pattern: /{languageCode}/aktualnosci/przelacz/{newsSlug}
    defaults: {_controller: GeniusDesignBackendBundle:News:togglePublished, languageCode: ''}
    requirements:
        newsSlug: "[\w-]+"
        languageCode: "[\w-]+"
    
genius_news_list:
    pattern: /{languageCode}/aktualnosci
    defaults: {_controller: GeniusDesignBackendBundle:News:list, languageCode: ''}



genius_content_edit:
    pattern: /{languageCode}/tresci/edycja/{contentSlug}
    defaults: {_controller: GeniusDesignBackendBundle:Content:edit, languageCode: ''}
    requirements:
        contentSlug: "[\w-]+"
        languageCode: "[\w-]+"

genius_content_list:
    pattern: /{languageCode}/tresci
    defaults: {_controller: GeniusDesignBackendBundle:Content:list, languageCode: ''}
    requirements:
        languageCode: "[\w-]+"


genius_homepage:
    pattern: /{languageCode}
    defaults: {_controller: GeniusDesignBackendBundle:Content:list, languageCode: ''}
    requirements:
        languageCode: "[\w-]+"


