genius_login:
    pattern: /logowanie
    defaults: {_controller: GeniusDesignBackendBundle:Security:login}
    
genius_login_check:
    pattern: /zaloguj
    
genius_logout:
    pattern: /wyloguj
    
    
    
genius_news_edit:
    pattern: /aktualnosci/edycja/{newsSlug}/{language}
    defaults: {_controller: GeniusDesignBackendBundle:News:edit, language: ''}
    requirements:
        contentSlug: "[\w-]+"
        language: "[\w-]+"
        
genius_news_add:
    pattern: /aktualnosci/dodaj/{language}
    defaults: {_controller: GeniusDesignBackendBundle:News:add, language: ''}
    requirements:
        language: "[\w-]+"

genius_news_delete:
    pattern: /aktualnosci/usun/{newsSlug}/{language}
    defaults: {_controller: GeniusDesignBackendBundle:News:delete, language: ''}
    requirements:
        newsSlug: "[\w-]+"
        language: "[\w-]+"
        
genius_news_toggle_published:
    pattern: /aktualnosci/przelacz/{newsSlug}/{language}
    defaults: {_controller: GeniusDesignBackendBundle:News:togglePublished, language: ''}
    requirements:
        newsSlug: "[\w-]+"
        language: "[\w-]+"
    
genius_news_list:
    pattern: /aktualnosci/{language}
    defaults: {_controller: GeniusDesignBackendBundle:News:list, language: ''}



genius_content_edit:
    pattern: /tresci/edycja/{contentSlug}/{language}
    defaults: {_controller: GeniusDesignBackendBundle:Content:edit, language: ''}
    requirements:
        contentSlug: "[\w-]+"
        language: "[\w-]+"

genius_content_list:
    pattern: /tresci/{language}
    defaults: {_controller: GeniusDesignBackendBundle:Content:list, language: ''}
    requirements:
        language: "[\w-]+"


genius_homepage:
    pattern: /{language}
    defaults: {_controller: GeniusDesignBackendBundle:Content:list, language: ''}
    requirements:
        language: "[\w-]+"


