# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

GeniusDesignDesktopPanelBundle:
    resource: "@GeniusDesignDesktopPanelBundle/Resources/config/routing.yml"
    prefix:   /admin

#GeniusDesignSiteBundle:
#    resource: "@SitePresentationBundle/Resources/config/routing.yml"
#    prefix:   /
