jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        GeniusDesign\BackendBundle\Entity\Admin:
            algorithm: md5
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: {class: GeniusDesign\BackendBundle\Entity\Admin, property: email}
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/admin/logowanie$
            anonymous: ~
        
        secured_area:
            #pattern: ^/
            pattern: ^/admin
            #anonymous: ~
            form_login:
                login_path: /admin/logowanie
                check_path: /admin/zaloguj
                failure_path: /admin/logowanie
                username_parameter: loginForm[email]
                password_parameter: loginForm[password]
                default_target_path: /admin
            logout:
                path: /admin/wyloguj
                target: /admin

    access_control:
        - {path: ^/admin/logowanie, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/admin, roles: ROLE_ADMIN}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}