simple_user_logout:
    pattern: /uzytkownik/wyloguj-sie
    defaults: {_controller: GeniusDesignComponentsSimpleUserBundle:SimpleUser:logout}
    
simple_user_login:
    pattern: /uzytkownik/zaloguj-sie
    defaults: {_controller: GeniusDesignComponentsSimpleUserBundle:SimpleUser:login}
        


genius_frontend_news_single:
    pattern: /{languageCode}/aktualnosc/{newsSlug}
    defaults: {_controller: GeniusDesignFrontendBundle:News:single, languageCode: ''}
    requirements:
        languageCode: "[\w-]+"
        newsSlug:  "[\w-]+"

genius_frontend_news_list:
    pattern: /{languageCode}/aktualnosci
    defaults: {_controller: GeniusDesignFrontendBundle:News:list, languageCode: ''}
    requirements:
        languageCode: "[\w-]+"
        
genius_frontend_common:
    pattern: /{languageCode}/{slug}
    defaults: {_controller: GeniusDesignFrontendBundle:Frontend:index, languageCode: '', slug: ''}
    requirements:
        languageCode: "[\w-]+"
        slug: "[\w-]+"

genius_frontend_main:
    pattern: /{languageCode}
    defaults: {_controller: GeniusDesignFrontendBundle:Frontend:index, languageCode: ''}
    requirements:
        languageCode: "[\w-]+"
