parameters:
#    genius_design_frontend.example.class: GeniusDesign\FrontendBundle\Example

services:
#    genius_design_frontend.example:
#        class: %genius_design_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
