parameters:
    genius_design_frontend.twig.extension.class: GeniusDesign\FrontendBundle\Twig\Extension\GeniusDesignFrontendExtension
    
services:
    genius_design_frontend.twig.extension:
        class: %genius_design_frontend.twig.extension.class%
        arguments:
            container: "@service_container"
        shared: true
        tags:
            - {name: twig.extension}