parameters:
#    genius_design_components_simple_user.example.class: GeniusDesign\Components\SimpleUserBundle\Example

services:
#    genius_design_components_simple_user.example:
#        class: %genius_design_components_simple_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
