parameters:
    genius_design_simple_user.helper.class: GeniusDesign\Components\SimpleUserBundle\Helper\SimpleUserHelper
    genius_design_simple_user.twig.extension.class: GeniusDesign\Components\SimpleUserBundle\Twig\Extension\GeniusDesignSimpleUserExtension
    
services:
    genius_design_simple_user.helper:
        class: %genius_design_simple_user.helper.class%
        arguments:
            container: "@service_container"
        shared: true
    genius_design_simple_user.twig.extension:
        class: %genius_design_simple_user.twig.extension.class%
        arguments:
            container: "@service_container"
        shared: true
        tags:
            - {name: twig.extension}