parameters:
#    genius_design_common.example.class: GeniusDesign\CommonBundle\Example

services:
#    genius_design_common.example:
#        class: %genius_design_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
