parameters:
#    genius_design_components_language.example.class: GeniusDesign\Components\LanguageBundle\Example

services:
#    genius_design_components_language.example:
#        class: %genius_design_components_language.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
