parameters:
    genius_design_language.helper.class: GeniusDesign\Components\LanguageBundle\Helper\LanguageHelper
    genius_design_language.twig.extension.class: GeniusDesign\Components\LanguageBundle\Twig\Extension\GeniusDesignLanguageExtension
    
services:
    genius_design_language.helper:
        class: %genius_design_language.helper.class%
        arguments:
            container: "@service_container"
        shared: true
    genius_design_language.twig.extension:
        class: %genius_design_language.twig.extension.class%
        arguments:
            container: "@service_container"
        shared: true
        tags:
            - {name: twig.extension}